Repository Learning-Hour-CS-Study/Learning-Hour, pull requests merged in 2025-03, with the labels that each got.

#42 [ 석찬] 인터럽트 발표 자료
  2_OS/05_os_interrupt.md
  2_OS/img/05_interrupt/1.png
Labels: OS, 발표

#43 [은비] 시스템 콜 발표 자료
  2_OS/06_os_systemcall.md
  2_OS/img/06_systemcall/01.png
  2_OS/img/06_systemcall/02.png
  2_OS/img/06_systemcall/03.png
Labels: OS, 발표

#46 [주환] PCB와 Context Switching 발표 자료
  2_OS/07_os_pcb_and_context_switching.md
  2_OS/img/07_pcb_and_context_switching.md/contextSwitching.png
  2_OS/img/07_pcb_and_context_switching.md/pcb.png
Labels: OS, 발표

#45 [장우] 주소 변환 발표 자료
  2_OS/09_os_address_translation.md
  2_OS/img/09_address_translation/1.png
  2_OS/img/09_address_translation/2.png
Labels: OS, 발표

#47 [소현] 주소 공간과 가상 메모리 발표 자료
  2_OS/08_Address Space_Virtual Memory.md
  2_OS/img/08_Address Space_Virtual Memory/1.png
  2_OS/img/08_Address Space_Virtual Memory/10.png
  2_OS/img/08_Address Space_Virtual Memory/11.png
  2_OS/img/08_Address Space_Virtual Memory/12.png
  2_OS/img/08_Address Space_Virtual Memory/13.png
  2_OS/img/08_Address Space_Virtual Memory/14.png
  2_OS/img/08_Address Space_Virtual Memory/2.png
  2_OS/img/08_Address Space_Virtual Memory/3.png
  2_OS/img/08_Address Space_Virtual Memory/4.png
  2_OS/img/08_Address Space_Virtual Memory/5.png
  2_OS/img/08_Address Space_Virtual Memory/6.png
  2_OS/img/08_Address Space_Virtual Memory/7.png
  2_OS/img/08_Address Space_Virtual Memory/8.png
  2_OS/img/08_Address Space_Virtual Memory/9.png
Labels: OS, 발표

#49 [주환] 가상메모리와 요구 페이징, 페이지 교체 발표자료
  2_OS/12_os_virtual_memory_and_demand_paging.md
  2_OS/img/12_virtual_memory_and_demand_paging/fifo.png
  2_OS/img/12_virtual_memory_and_demand_paging/lru.png
  2_OS/img/12_virtual_memory_and_demand_paging/opt.png
  2_OS/img/12_virtual_memory_and_demand_paging/page_fault.png
Labels: OS, 발표

#51 [은비] 페이징 발표 자료
  2_OS/10_os_paging.md
  2_OS/img/10_paging/1.png
  2_OS/img/10_paging/2.png
  2_OS/img/10_paging/3.png
Labels: OS, 발표

#50 docs: 세그먼트 파일 작성
  2_OS/10_os_segmentation.md
  2_OS/img/10_segmentation/1.png
  2_OS/img/10_segmentation/2.png
  2_OS/img/10_segmentation/3.png
Labels: OS, 발표

#52 [주환] 퀴즈 추가
  2_OS/12_os_virtual_memory_and_demand_paging.md
Labels: OS, Add

#53 [은비] 파일명 수정
  2_OS/11_os_paging.md
Labels: OS, File

#55 [chore] 주소 공간과 가상 메모리 내용 수정
  2_OS/08_Address Space_Virtual Memory.md
  2_OS/img/08_Address Space_Virtual Memory/14.png
Labels: Fix, OS

#56 [장우] 동기화(스핀락, 뮤텍스, 세마포어) 발표 자료
  2_OS/14_os_synchronization.md
  2_OS/img/14_synchronization/1.jpg
  2_OS/img/14_synchronization/10.png
  2_OS/img/14_synchronization/11.png
  2_OS/img/14_synchronization/2.jpg
  2_OS/img/14_synchronization/3.jpg
  2_OS/img/14_synchronization/4.jpg
  2_OS/img/14_synchronization/5.jpg
  2_OS/img/14_synchronization/6.png
  2_OS/img/14_synchronization/7.png
  2_OS/img/14_synchronization/8.png
  2_OS/img/14_synchronization/9.png
  2_OS/img/14_synchronization/img.gif
Labels: OS, 발표

#57 [소현] TLB 발표 자료
  2_OS/13_os_tlb.md
  2_OS/img/13_TLB/1.png
  2_OS/img/13_TLB/2.png
Labels: OS, 발표

#59 [은비] 멀티프로세스, 스레드, 멀티스레드 발표 자료
  2_OS/16_os_multi_procsss_thread_multi_thread.md
  2_OS/img/16_multi_process_thread_multi_thread/1.png
  2_OS/img/16_multi_process_thread_multi_thread/2.png
  2_OS/img/16_multi_process_thread_multi_thread/3.png
  2_OS/img/16_multi_process_thread_multi_thread/4.png
  2_OS/img/16_multi_process_thread_multi_thread/5.png
Labels: OS, 발표

#60 [장우] 동기화 발표 자료 내용 추가
  2_OS/14_os_synchronization.md
  2_OS/img/14_synchronization/12.png
Labels: OS, Add

#64 [주환] 대역폭 발표 자료
  3_Network/02_network_bandwidth.md
Labels: Network, 발표

#65 [소현] OSI 7계층 발표 자료
  3_Network/03_network_osi_7_layer.md
  3_Network/img/03_osi_7_layer/1.png
  3_Network/img/03_osi_7_layer/2.png
Labels: Network, 발표

#66 [석찬] DNS + 웹 통신 흐름 발표자료
  3_Network/05_network_dns_web_flow.md
  3_Network/img/05_network_dns_web_flow/1.png
  3_Network/img/05_network_dns_web_flow/2.png
  3_Network/img/05_network_dns_web_flow/3.png
Labels: Network, 발표

#67 [은비] 네트워크 기초 발표 자료
  3_Network/01_network_basic.md
  3_Network/img/01_network_basic/1.gif
  3_Network/img/01_network_basic/2.png
  3_Network/img/01_network_basic/3.png
  3_Network/img/01_network_basic/4.png
Labels: Network, 발표
