Repository Learning-Hour-CS-Study/Learning-Hour, pull requests merged in 2025-04, with the labels that each got.

#70 [주환] L7/L4 스위치, 로드밸런싱 발표 자료
  3_Network/07_network_l4_l7_switch_and_load_balancing.md
  3_Network/img/07_network_l4_l7_switch_and_load_balancing/after_load_balancer.png
  3_Network/img/07_network_l4_l7_switch_and_load_balancing/before_load_balancer.png
  3_Network/img/07_network_l4_l7_switch_and_load_balancing/ip_hash.png
  3_Network/img/07_network_l4_l7_switch_and_load_balancing/round_robin.png
  3_Network/img/07_network_l4_l7_switch_and_load_balancing/weight_round_robin.png
Labels: Network, 발표

#71 [소현] HTTP 진화 과정 발표자료
  3_Network/08_network_http.md
  3_Network/img/08_http/1.png
  3_Network/img/08_http/2.png
  3_Network/img/08_http/3.png
  3_Network/img/08_http/4.png
  3_Network/img/08_http/5.png
  3_Network/img/08_http/6.gif
Labels: Network, 발표

#72 [은비] 네크워크 기기 발표 자료
  3_Network/06_network_devices.md
  3_Network/img/06_network_devices/1.png
  3_Network/img/06_network_devices/2.png
  3_Network/img/06_network_devices/3.png
Labels: Network, 발표

#73 [석찬] REST API + RESTful 발표 자료
  3_Network/10_network_rest_api_restful.md
Labels: Network, 발표, 퀴즈

#74 [소현] OSI 7계층 내용 수정
  3_Network/03_network_osi_7_layer.md
Labels: Network, File

#76 [장우] 프록시 서버 발표 자료
  3_Network/13_network_proxy_server.md
  3_Network/img/13_proxy_server/1.png
  3_Network/img/13_proxy_server/2.png
  3_Network/img/13_proxy_server/3.png
  3_Network/img/13_proxy_server/4.png
Labels: Network, 발표

#78 [주환] SOAP 발표자료
  3_Network/11_network_soap.md
  3_Network/img/11_network_soap/soap_req_res.png
Labels: Network, 발표

#79 [석찬] SOP & CORS 발표자료
  3_Network/14_sop_and_cors.md
  3_Network/img/14_sop_cors/1.png
  3_Network/img/14_sop_cors/2.png
  3_Network/img/14_sop_cors/3.png
Labels: Network, 발표, 퀴즈

#82 [장우] 동시성 제어 발표 자료
  4_Database/04_db_concurrency_control.md
  4_Database/img/04_transaction_concurrency_control/1.png
  4_Database/img/04_transaction_concurrency_control/10.png
  4_Database/img/04_transaction_concurrency_control/11.png
  4_Database/img/04_transaction_concurrency_control/12.png
  4_Database/img/04_transaction_concurrency_control/13.png
  4_Database/img/04_transaction_concurrency_control/14.png
  4_Database/img/04_transaction_concurrency_control/15.png
  4_Database/img/04_transaction_concurrency_control/16.png
  4_Database/img/04_transaction_concurrency_control/17.png
  4_Database/img/04_transaction_concurrency_control/18.png
  4_Database/img/04_transaction_concurrency_control/19.png
  4_Database/img/04_transaction_concurrency_control/2.png
  4_Database/img/04_transaction_concurrency_control/20.png
  4_Database/img/04_transaction_concurrency_control/21.png
  4_Database/img/04_transaction_concurrency_control/22.png
  4_Database/img/04_transaction_concurrency_control/23.png
  4_Database/img/04_transaction_concurrency_control/24.png
  4_Database/img/04_transaction_concurrency_control/25.png
  4_Database/img/04_transaction_concurrency_control/3.png
  4_Database/img/04_transaction_concurrency_control/4.png
  4_Database/img/04_transaction_concurrency_control/5.png
  4_Database/img/04_transaction_concurrency_control/6.png
  4_Database/img/04_transaction_concurrency_control/7.png
  4_Database/img/04_transaction_concurrency_control/8.png
  4_Database/img/04_transaction_concurrency_control/9.png
Labels: DB, 발표

#83 [석찬] Isolation level 및 이상현상 발표자료
  4_Database/05_database_isolation_level.md
Labels: DB, 발표, 퀴즈

#84 [주환] ERD와 정규화 과정 발표자료
  4_Database/02_db_erd_normalization.md
  4_Database/img/02_erd_normalization/after_1.png
  4_Database/img/02_erd_normalization/after_2.png
  4_Database/img/02_erd_normalization/after_3.png
  4_Database/img/02_erd_normalization/attribute.png
  4_Database/img/02_erd_normalization/bad1.png
  4_Database/img/02_erd_normalization/bad2.png
  4_Database/img/02_erd_normalization/before_1.png
  4_Database/img/02_erd_normalization/change_2.png
  4_Database/img/02_erd_normalization/change_3.png
  4_Database/img/02_erd_normalization/change_bcnf.png
  4_Database/img/02_erd_normalization/determinant.png
  4_Database/img/02_erd_normalization/domain.png
  4_Database/img/02_erd_normalization/entity.png
  4_Database/img/02_erd_normalization/entity_example.png
  4_Database/img/02_erd_normalization/full_dependency.png
  4_Database/img/02_erd_normalization/many_to_many.png
  4_Database/img/02_erd_normalization/multi_dependency.png
  4_Database/img/02_erd_normalization/notation.jpg
  4_Database/img/02_erd_normalization/one_to_many.png
  4_Database/img/02_erd_normalization/one_to_one.png
  4_Database/img/02_erd_normalization/participation.png
  4_Database/img/02_erd_normalization/relationship1.png
  4_Database/img/02_erd_normalization/relationship2.png
  4_Database/img/02_erd_normalization/summary_normalization.png
Labels: DB, 발표

#86 [은비] key 발표자료
  4_Database/01_db_key.md
Labels: DB, 발표

#85 [소현] 트랜잭션 개념과 ACID 속성 발표자료
  4_Database/03_db_transaction_and_acid.md
  4_Database/img/03_db_transaction_and_acid/1.png
  4_Database/img/03_db_transaction_and_acid/2.png
  4_Database/img/03_db_transaction_and_acid/3.png
  4_Database/img/03_db_transaction_and_acid/4.png
  4_Database/img/03_db_transaction_and_acid/5.png
  4_Database/img/03_db_transaction_and_acid/6.png
  4_Database/img/03_db_transaction_and_acid/7.png
Labels: DB, 발표

#89 [장우] 저장 프로시저 발표자료
  4_Database/09_db_stored_procedure.md
  4_Database/img/09_stored_procedure/1.png
  4_Database/img/09_stored_procedure/2.png
  4_Database/img/09_stored_procedure/3.png
  4_Database/img/09_stored_procedure/4.png
  4_Database/img/09_stored_procedure/5.png
  4_Database/img/09_stored_procedure/6.png
  4_Database/img/09_stored_procedure/7.png
  4_Database/img/09_stored_procedure/8.png
  4_Database/img/09_stored_procedure/9.png
Labels: DB, 발표

#92 [주환] 인덱스 발표 자료
  4_Database/07_db_index.md
  4_Database/img/07_index/tree.png
  4_Database/img/07_index/tree2.png
Labels: DB, 발표

#91 [석찬] Schema 발표자료
  4_Database/10_db_schema.md
  4_Database/img/10_schema/1.png
Labels: DB, 발표, 퀴즈

#90 [소현] DB 인덱스 발표자료
  4_Database/08_database_join.md
  4_Database/08_db_index.md
  4_Database/img/08_database_join/1.png
  4_Database/img/08_database_join/10.png
  4_Database/img/08_database_join/11.png
  4_Database/img/08_database_join/12.png
  4_Database/img/08_database_join/2.png
  4_Database/img/08_database_join/3.png
  4_Database/img/08_database_join/4.png
  4_Database/img/08_database_join/5.png
  4_Database/img/08_database_join/6.png
  4_Database/img/08_database_join/7.png
  4_Database/img/08_database_join/8.png
  4_Database/img/08_database_join/9.png
  4_Database/img/08_db_index/1.png
  4_Database/img/08_db_index/10.png
  4_Database/img/08_db_index/2.png
  4_Database/img/08_db_index/3.png
  4_Database/img/08_db_index/4.png
  4_Database/img/08_db_index/5.png
  4_Database/img/08_db_index/6.png
  4_Database/img/08_db_index/7.png
  4_Database/img/08_db_index/8.png
  4_Database/img/08_db_index/9.png
Labels: DB, 발표

#93 [은비] RDBMS와 NoSQL 발표 자료
  4_Database/06_db_.md
  4_Database/img/05_rdbms_and_nosql/image.png
Labels: DB, 발표

#94 [주환] 08_db_index.md 삭제
  4_Database/08_db_index.md
Labels: DB, File

#95 [은비] 파일 이름 수정
  4_Database/06_db_rdbms_and_nosql.md
Labels: DB, File
